language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
script:
  - set -o pipefail
  - xcodebuild -project VZInspectorDemo.xcodeproj -scheme VZInspectorDemo -sdk iphonesimulator 
  


